
# Network Infrastructure testing for pScheduler
# Developed by Nathan Shepherd for UofM:ITS

# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|

    server.vm.box = "geerlingguy/centos7"

    server.vm.network "public_network", ip: "172.28.128.3" #type: "dhcp"

    server.vm.hostname = "server"

    server.vm.provision "shell", inline: <<-SHELL
       sudo yum install -y git docker
       sudo systemcl start docker

       git clone https://github.com/perfsonar/perfsonar-testpoint-docker.git

       cd perfsonar-testpoint-docker
       git checkout tags/4.0.2.3
       cd ..

       git clone https://github.com/CiscoIOx/perfsonar.git
       cp -r ./perfsonar/CISCO_IOX/ perfsonar-testpoint-docker/
       cd perfsonar-testpoint-docker

       sudo make build



    SHELL

  end # vm.define

end # configure 
